export const Images = {
  moon: require("assets/moon.png"),
  direction: require("assets/direction.png"),
  water: require("assets/water.png"),
  rainy: require("assets/rainy.png"),
  cloud: require("assets/cloud.png"),
  next: require("assets/next.png"),
  location: require("assets/location.png"),
  search: require("assets/search.png"),
  topCloud: require("assets/topCloud.png"),
  hourHand: require("assets/Hour Hand.png"),
  secondHand: require("assets/Seconds Hand.png"),
  vector1: require("assets/Vector-1.png"),
  vector2: require("assets/Vector2.png"),
  vector3: require("assets/Vector3.png"),
  vector4: require("assets/Vector4.png"),
  vector5: require("assets/Vector5.png"),
  vector6: require("assets/Vector6.png"),
  ellipse: require("assets/Ellipse 35.png"),
};
